# Generated by Django 5.0.1 on 2024-01-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='CustomersInfo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalAmount',
        ),
        migrations.AddField(
            model_name='order',
            name='coffee_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
