# Generated by Django 5.0.1 on 2024-01-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_order_customersinfo_remove_order_orderdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='CustomersInfo',
            new_name='customer_info',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CustomersInfo',
            new_name='customer_info',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='CustomersInfo',
            new_name='customer_info',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionDate',
            new_name='transaction_date',
        ),
        migrations.AlterField(
            model_name='customersinfo',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
