# Generated by Django 5.0.1 on 2024-01-31 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_customersinfo_orderdetail_customer_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coffee_type',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.product'),
        ),
    ]
